# Site settings
title: "Dan Robertson"
description: "Dan Robertson's website"
url: "http://dlrobertson.com"
baseurl: ""

#  Build settings
permalink: "/blog/:categories/:year/:month/:day/:title.html"
highlighter: rouge

plugins:
  - jekyll-redirect-from
  - jekyll-paginate

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

exclude: ["slides/reveal.js/demo.html", "slides/reveal.js/index.html"]
